filter:
    excluded_paths:
        - 'vendor/*'

tools:
    php_mess_detector:
        config:
            controversial_rules: { superglobals: false }
    php_cpd: true
    php_pdepend: true
    php_code_coverage: false
    php_code_sniffer: true
    php_cs_fixer: true
    php_loc: true
    php_analyzer: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: '600'

checks:
    php:
        psr2_class_declaration: false
        psr2_switch_declaration: false
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        no_eval: true
        code_rating: true
        duplication: true
		simplify_boolean_return: true
        properties_in_camelcaps: true
        parameter_doc_comments: true
        overriding_parameter: true
        no_goto: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
