#####
# This file is part of the MediaWiki Extension BootstrapComponents.
#
# @copyright 2018, Tobias Oetterer
# @license   GNU General Public License, version 3 (or any later version)
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# @file
#
# @author  Tobias Oetterer
# @since   1.0
# @ingroup BootstrapComponents
#####

language: php
sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 7.1
    - env: DBTYPE=mysql; MW=1.30.1
      php: 5.6
    - env: DBTYPE=mysql; MW=1.27.3; TYPE=coverage
      php: 5.6


install:
  - bash ./tests/travis/install-system.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
